apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-grpc
  name: udaconnect-location-grpc
spec:
  ports:
  - name: "5000"
    port: 5005
    targetPort: 5005
    nodePort: 30004
  selector:
    service: udaconnect-location-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-grpc
  name: udaconnect-location-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-grpc
  template:
    metadata:
      labels:
        service: udaconnect-location-grpc
    spec:
      containers:
      - image: nghiahv1/udaconnect-location-grpc:latest
        name: udaconnect-location-grpc
        imagePullPolicy: Always
        env:
        - name: KAFKA_TOPIC
          value: "test"
        - name: KAFKA_HOST
          value: "192.168.81.129"
        - name: KAFKA_PORT
          value: "9092"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
